name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pacman SVG
        uses: Platane/animated-pacman-github-contribution-graph@v1.0.0
        with:
          github_user_name: lnoliver96
          output_path: output/pacman-contribution-graph.svg

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate Pacman Contribution Graph"
          add: "output/*"
